# Generated by Django 6.0.3 on 2026-05-09 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0005_alter_bookmark_date_bookmarked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'verbose_name': 'Bookmark', 'verbose_name_plural': 'Bookmarks'},
        ),
        migrations.AlterModelOptions(
            name='bookreview',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='borrow',
            options={'verbose_name': 'Borrow', 'verbose_name_plural': 'Borrows'},
        ),
    ]
