# Generated by Django 6.0.3 on 2026-05-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0003_project_creator_project_status_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreview',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
    ]
