# Generated by Django 6.0.3 on 2026-05-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0004_alter_projectreview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreview',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
