# Generated by Django 6.0.3 on 2026-05-09 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0006_remove_project_status_favorite_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='status',
            new_name='project_status',
        ),
    ]
