# Generated by Django 6.0.3 on 2026-05-09 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0007_rename_status_favorite_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='project_status',
            field=models.CharField(choices=[('Backlog', 'Backlog'), ('To-Do', 'To-Do'), ('Done', 'Done')], default='Backlog', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectrating',
            name='score',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
